//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stockmanagmentapp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int id { get; set; }
        public string productname { get; set; }
        public int categoryid { get; set; }
        public int stockamount { get; set; }
        public int price { get; set; }
        public bool isdeleted { get; set; }
        public Nullable<System.DateTime> deleteddate { get; set; }
    }
}
